name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    container: python:${{ matrix.python-version }}-slim
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src --count --max-complexity=10 --max-line-length=127 --statistics
    - name: Type check with MyPy
      run: mypy src
    - name: Security check with Bandit
      run: bandit -r src
    - name: Run unit tests with pytests
      run: pytest -v --tb=short --color=yes --cov=src --cov-report=term-missing
